Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 135
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 100
