sudo: required
dist: trusty
notifications:
  email: false
language: ruby
rvm:
  - 2.4.2
env:
  - ROBOT_ENV=test
cache:
  bundler: true
script:
  - bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=56870920cf4817ced14b907140d61cbe42941a42781667d0a62f139275e86efa bundle exec codeclimate-test-reporter
