version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install
build: off
test_script:
  - set ROBOT_ENV=test
  - bundle exec rspec
